### ISSUE TITLE
0.8.0 之后的版本我都用不了了，vite.config直接报错

### ISSUE THREAD

**Issue by IllegalCreed** [Jevon617/unplugin-svg-component#23]
> beitou-protals@0.0.0 dev
> vite

failed to load config from /Users/zhangxu/workspace/beitou-protals/code/gitlab/beitou-protals/vite.config.ts
error when starting dev server:
Error: Dynamic require of "tty" is not supported
    at file:///Users/zhangxu/workspace/beitou-protals/code/gitlab/beitou-protals/node_modules/unplugin-svg-component/dist/chunk-HBZT7EOT.js:26:9
    at node_modules/.pnpm/picocolors@1.0.1/node_modules/picocolors/picocolors.js (file:///Users/zhangxu/workspace/beitou-protals/code/gitlab/beitou-protals/node_modules/unplugin-svg-component/dist/chunk-HBZT7EOT.js:54:189)
    at __require2 (file:///Users/zhangxu/workspace/beitou-protals/code/gitlab/beitou-protals/node_modules/unplugin-svg-component/dist/chunk-HBZT7EOT.js:29:50)
    at file:///Users/zhangxu/workspace/beitou-protals/code/gitlab/beitou-protals/node_modules/unplugin-svg-component/dist/chunk-HBZT7EOT.js:539:33
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
    at async loadConfigFromBundledFile (file:///Users/zhangxu/workspace/beitou-protals/code/gitlab/beitou-protals/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:68675:21)
    at async loadConfigFromFile (file:///Users/zhangxu/workspace/beitou-protals/code/gitlab/beitou-protals/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:68528:28)
    at async resolveConfig (file:///Users/zhangxu/workspace/beitou-protals/code/gitlab/beitou-protals/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:68138:28)
    at async _createServer (file:///Users/zhangxu/workspace/beitou-protals/code/gitlab/beitou-protals/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:64655:20)

退回到0.8.0用起来就没有任何问题

**Comment by Jevon617** [comment]
@IllegalCreed 感谢反馈, 可以给我一个复现的demo吗, 还有环境信息.

**Comment by 2815261401** [comment]
https://stackblitz.com/edit/vitejs-vite-j4xfjt?file=vite.config.ts&terminal=dev'

**Comment by IllegalCreed** [comment]
> @IllegalCreed 感谢反馈, 可以给我一个复现的demo吗, 还有环境信息.

https://github.com/IllegalCreed/svgDemo   用的vite默认模板做的，例子在about标签下，但这其实不重要，所有大于0.8.0的版本启动不了，我看了看0.8.0到0.9.0的更新，除了换了个svg的大依赖，其他应该也没啥了，不清楚问题出在哪，大佬看看吧。

**Comment by IllegalCreed** [comment]
> > @IllegalCreed 感谢反馈, 可以给我一个复现的demo吗, 还有环境信息.
> 
> https://github.com/IllegalCreed/svgDemo 用的vite默认模板做的，例子在about标签下，但这其实不重要，所有大于0.8.0的版本启动不了，我看了看0.8.0到0.9.0的更新，除了换了个svg的大依赖，其他应该也没啥了，不清楚问题出在哪，大佬看看吧。

 System:
    OS: macOS 14.5
    CPU: (11) arm64 Apple M3 Pro
    Memory: 66.20 MB / 18.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
    npm: 10.5.0 - ~/.nvm/versions/node/v20.12.2/bin/npm
    pnpm: 9.1.2 - ~/.nvm/versions/node/v20.12.2/bin/pnpm
  Browsers:
    Chrome: 125.0.6422.77
    Edge: 125.0.2535.67
    Safari: 17.5

**Comment by IllegalCreed** [comment]
感觉是esbuild打包之后才会有的问题，如果直接依赖源码应该不会出问题，查了查感觉是esbuild外部依赖配置的问题，不确定是不是这个导致的

**Comment by Jevon617** [comment]
@IllegalCreed 是我错误的把picocolors 装到了devDependencies, 导致打包的文件有问题.

**Comment by Jevon617** [comment]
@IllegalCreed 最新版本解决了这个问题.

**Comment by IllegalCreed** [comment]
> @IllegalCreed 最新版本解决了这个问题.

谢谢大佬，感恩
